services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wget xfonts-base xfonts-75dpi
      wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.6/wkhtmltox_0.12.6-1.bionic_amd64.deb
      apt install -y ./wkhtmltox_0.12.6-1.bionic_amd64.deb
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_SHEET_NAME
        value: your-google-sheet-name
