<<<<<<< HEAD
services:
  - type: web
    name: my-app
    env: python
    buildCommand: ./render-build.sh
    startCommand: python app.py
    plan: free
=======
services:
  - type: web
    name: pdf-generator
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wget xfonts-base xfonts-75dpi
      wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.6/wkhtmltox_0.12.6-1.bionic_amd64.deb
      apt install -y ./wkhtmltox_0.12.6-1.bionic_amd64.deb
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_SHEET_NAME
        value: YOUR_SHEET_NAME_HERE
>>>>>>> f524e1591a8dbdefaba05cbc083bec0ddc16b284
